//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_ENTITY.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSO()
        {
            this.REPORTE = new HashSet<REPORTE>();
        }
    
        public decimal cu_id { get; set; }
        public Nullable<decimal> am_id { get; set; }
        public Nullable<decimal> pf_id { get; set; }
        public Nullable<decimal> pe_id { get; set; }
        public Nullable<decimal> so_id { get; set; }
        public Nullable<int> cu_code { get; set; }
        public string cu_name { get; set; }
        public Nullable<int> cu_duration { get; set; }
        public Nullable<System.DateTime> cu_startdate { get; set; }
        public Nullable<System.DateTime> cu_enddate { get; set; }
        public string cu_note { get; set; }
        public string cu_days { get; set; }
    
        public virtual AMBIENTE AMBIENTE { get; set; }
        public virtual PROGRAMA_ESPECIAL PROGRAMA_ESPECIAL { get; set; }
        public virtual PROGRAMA_FORMACION PROGRAMA_FORMACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE> REPORTE { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
