//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_ENTITY.ModelEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FC_DB : DbContext
    {
        public FC_DB()
            : base("name=FC_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMBIENTE> AMBIENTE { get; set; }
        public virtual DbSet<CORDINADORA> CORDINADORA { get; set; }
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<INSTRUCTOR> INSTRUCTOR { get; set; }
        public virtual DbSet<LOCACION> LOCACION { get; set; }
        public virtual DbSet<PROGRAMA_ESPECIAL> PROGRAMA_ESPECIAL { get; set; }
        public virtual DbSet<PROGRAMA_FORMACION> PROGRAMA_FORMACION { get; set; }
        public virtual DbSet<REPORTE> REPORTE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUD { get; set; }
    
        public virtual ObjectResult<getSolicitudesGPT_Result> getSolicitudesGPT(Nullable<int> us_nid, string so_status)
        {
            var us_nidParameter = us_nid.HasValue ?
                new ObjectParameter("us_nid", us_nid) :
                new ObjectParameter("us_nid", typeof(int));
    
            var so_statusParameter = so_status != null ?
                new ObjectParameter("so_status", so_status) :
                new ObjectParameter("so_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSolicitudesGPT_Result>("getSolicitudesGPT", us_nidParameter, so_statusParameter);
        }
    
        public virtual ObjectResult<getSolicitudesPrueba_Result> getSolicitudesPrueba()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSolicitudesPrueba_Result>("getSolicitudesPrueba");
        }
    
        public virtual ObjectResult<Nullable<int>> ValidarUsuario(Nullable<decimal> us_nid)
        {
            var us_nidParameter = us_nid.HasValue ?
                new ObjectParameter("us_nid", us_nid) :
                new ObjectParameter("us_nid", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidarUsuario", us_nidParameter);
        }
    }
}
