//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_ENTITY.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA_FORMACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROGRAMA_FORMACION()
        {
            this.CURSO = new HashSet<CURSO>();
        }
    
        public decimal pf_id { get; set; }
        public Nullable<int> pf_code { get; set; }
        public string pf_name { get; set; }
        public Nullable<double> pf_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURSO> CURSO { get; set; }
    }
}
