//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_ENTITY.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public decimal re_id { get; set; }
        public decimal cu_id { get; set; }
        public Nullable<System.DateTime> re_date { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
