//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_ENTITY.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD()
        {
            this.CURSO = new HashSet<CURSO>();
        }
    
        public decimal so_id { get; set; }
        public Nullable<decimal> co_id { get; set; }
        public Nullable<decimal> in_id { get; set; }
        public Nullable<int> so_name { get; set; }
        public string so_status { get; set; }
        public string so_type { get; set; }
        public string so_ente { get; set; }
        public Nullable<System.DateTime> so_date { get; set; }
    
        public virtual CORDINADORA CORDINADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURSO> CURSO { get; set; }
        public virtual INSTRUCTOR INSTRUCTOR { get; set; }
    }
}
