//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public decimal so_id { get; set; }
        public string so_status { get; set; }
        public Nullable<bool> so_type { get; set; }
        public string so_ente { get; set; }
        public Nullable<System.DateTime> so_date { get; set; }
        public Nullable<decimal> us_id { get; set; }
        public Nullable<decimal> cu_id { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
