//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA_ESPECIAL
    {
        public decimal pe_id { get; set; }
        public Nullable<decimal> pe_code { get; set; }
        public string pe_name { get; set; }
    }
}
